---
# I don't use these CI systems.
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true

common:
  honeycomb: false

.gitignore:
  paths:
    - '/html'
    - '.config/'
    - '.pdk/'

spec/spec_helper.rb:
  mock_with: ":rspec"

.devcontainer/README.md:
  delete: true
.devcontainer/devcontainer.json:
  unmanaged: true
