---
# I don't use these CI systems.
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true

spec/spec_helper.rb:
  mock_with: ':rspec'

.travis.yml:
  use_litmus: true
  litmus:
    provision_list: [travis_el]
  deploy: false
  dist: xenial
  stages:
    - static
    - acceptance
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    - env: DEPLOY_TO_FORGE=yes
      stage: deploy

.rubocop.yml:
  default_configs:
    AllCops:
      TargetRubyVersion: '2.4'
    Style/FrozenStringLiteralComment:
      Enabled: false
