---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      bundler_args:
      env: PLATFORM=centos:puppet5
      script: bundle exec rake 'litmus:provision_install[docker]' && bundle exec rake 'litmus:acceptance:parallel' && bundle exec rake 'litmus:tear_down'

      services: docker
      stage: acceptance
    -
      bundler_args:
      env: PLATFORM=centos:puppet6
      script: bundle exec rake 'litmus:provision_install[docker]' && bundle exec rake 'litmus:acceptance:parallel' && bundle exec rake 'litmus:tear_down'

      services: docker
      stage: acceptance
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
